# Generated by Django 4.2.21 on 2025-05-16 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200, primary_key=True, serialize=False, unique=True)),
                ('phonenumber', models.IntegerField(max_length=10)),
                ('password', models.CharField(max_length=500)),
            ],
        ),
    ]
