# Generated by Django 4.2.21 on 2025-05-18 19:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls_app', '0003_user_logintime'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='logouttime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
