# Generated by Django 4.2.21 on 2025-05-18 19:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls_app', '0004_user_logouttime'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginLogoutDetails',
            fields=[
                ('email', models.EmailField(max_length=200, primary_key=True, serialize=False, unique=True)),
                ('logintime', models.DateTimeField(default=django.utils.timezone.now)),
                ('logouttime', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='logintime',
        ),
        migrations.RemoveField(
            model_name='user',
            name='logouttime',
        ),
    ]
