# Generated by Django 4.2.21 on 2025-05-18 19:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls_app', '0005_loginlogoutdetails_remove_user_logintime_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LoginLogoutDetails',
        ),
        migrations.AddField(
            model_name='user',
            name='logintime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='user',
            name='logouttime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
