# Generated by Django 4.2.21 on 2025-05-19 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls_app', '0006_delete_loginlogoutdetails_user_logintime_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Polls',
            fields=[
                ('questionnumber', models.BigAutoField(primary_key=True, serialize=False)),
                ('authorname', models.CharField(max_length=200)),
                ('question', models.CharField(max_length=5000)),
                ('option1', models.CharField(max_length=200)),
                ('option2', models.CharField(max_length=200)),
                ('option3', models.CharField(max_length=200)),
                ('option4', models.CharField(max_length=200)),
            ],
        ),
    ]
