# Generated by Django 4.2.21 on 2025-05-19 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls_app', '0007_polls'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='polls',
            name='authorname',
        ),
        migrations.AddField(
            model_name='polls',
            name='authoremail',
            field=models.EmailField(default='example@email.com', max_length=200),
        ),
    ]
