# Generated by Django 4.2.21 on 2025-05-22 10:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls_app', '0009_polls_response1_polls_response2_polls_response3_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('messageid', models.BigAutoField(primary_key=True, serialize=False)),
                ('senderemail', models.EmailField(max_length=200)),
                ('receiveremail', models.EmailField(max_length=200)),
                ('message', models.CharField(max_length=5000)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('read', models.BooleanField(default=False)),
            ],
        ),
    ]
