# Generated by Django 4.2.21 on 2025-06-02 19:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls_app', '0011_examdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examdetails',
            name='endTime',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
        migrations.AlterField(
            model_name='examdetails',
            name='startDate',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='examdetails',
            name='startTime',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
    ]
