# Generated by Django 4.2.21 on 2025-06-09 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls_app', '0012_alter_examdetails_endtime_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamQuestions',
            fields=[
                ('questionid', models.BigAutoField(primary_key=True, serialize=False)),
                ('questionnumber', models.IntegerField(default=0)),
                ('examid', models.IntegerField(default=0)),
                ('question', models.CharField(max_length=5000)),
                ('option1', models.CharField(max_length=5000)),
                ('option2', models.CharField(max_length=5000)),
                ('option3', models.CharField(max_length=5000)),
                ('option4', models.CharField(max_length=5000)),
                ('positiveScore', models.IntegerField(default=0)),
                ('negativeScore', models.IntegerField(default=0)),
                ('correctOption', models.IntegerField(default=0)),
            ],
        ),
    ]
