# Generated by Django 4.2.21 on 2025-06-19 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls_app', '0013_examquestions'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, help_text='Optional profile picture', null=True, upload_to='profiles/'),
        ),
    ]
