# Generated by Django 4.2.21 on 2025-06-22 14:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls_app', '0014_user_profile_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamResponse',
            fields=[
                ('responseid', models.BigAutoField(primary_key=True, serialize=False)),
                ('examid', models.IntegerField(default=0)),
                ('email', models.EmailField(max_length=200)),
                ('questionid', models.IntegerField(default=0)),
                ('response', models.IntegerField(default=0)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='ExamResults',
            fields=[
                ('resultid', models.BigAutoField(primary_key=True, serialize=False)),
                ('examid', models.IntegerField(default=0)),
                ('email', models.EmailField(max_length=200)),
                ('score', models.IntegerField(default=0)),
                ('timeTaken', models.IntegerField(default=0)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('correctAnswers', models.IntegerField(default=0)),
                ('wrongAnswers', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='examquestions',
            name='explanation',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
