# Generated by Django 4.2.21 on 2025-06-23 18:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls_app', '0015_examresponse_examresults_examquestions_explanation'),
    ]

    operations = [
        migrations.CreateModel(
            name='PollQuestions',
            fields=[
                ('questionid', models.BigAutoField(primary_key=True, serialize=False)),
                ('authoremail', models.EmailField(default='example@email.com', max_length=200)),
                ('question', models.CharField(max_length=5000)),
                ('likes', models.IntegerField(default=0)),
                ('dislikes', models.IntegerField(default=0)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('image', models.ImageField(blank=True, help_text='Optional picture for the poll question', null=True, upload_to='profiles/')),
            ],
        ),
        migrations.CreateModel(
            name='PollResponses',
            fields=[
                ('optionid', models.BigAutoField(primary_key=True, serialize=False)),
                ('questionid', models.IntegerField(default=0)),
                ('optionDescription', models.CharField(max_length=5000)),
                ('response', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, help_text='Optional picture for the poll response', null=True, upload_to='profiles/')),
            ],
        ),
    ]
