# Generated by Django 4.2.21 on 2025-06-23 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls_app', '0016_pollquestions_pollresponses'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pollquestions',
            old_name='question',
            new_name='pollDescription',
        ),
    ]
