# Generated by Django 4.2.21 on 2025-06-24 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls_app', '0017_rename_question_pollquestions_polldescription'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Polls',
        ),
    ]
