# Generated by Django 4.2.21 on 2025-06-25 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls_app', '0018_delete_polls'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamOptions',
            fields=[
                ('optionid', models.BigAutoField(primary_key=True, serialize=False)),
                ('questionid', models.IntegerField(default=0)),
                ('optionDescription', models.CharField(max_length=5000)),
                ('positiveScore', models.IntegerField(default=0)),
                ('negativeScore', models.IntegerField(default=0)),
                ('isCorrect', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, help_text='Optional picture for the exam option', null=True, upload_to='profiles/')),
            ],
        ),
        migrations.RemoveField(
            model_name='examquestions',
            name='negativeScore',
        ),
        migrations.RemoveField(
            model_name='examquestions',
            name='option1',
        ),
        migrations.RemoveField(
            model_name='examquestions',
            name='option2',
        ),
        migrations.RemoveField(
            model_name='examquestions',
            name='option3',
        ),
        migrations.RemoveField(
            model_name='examquestions',
            name='option4',
        ),
        migrations.RemoveField(
            model_name='examquestions',
            name='positiveScore',
        ),
        migrations.AddField(
            model_name='examquestions',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional picture for the exam question', null=True, upload_to='profiles/'),
        ),
    ]
