# Generated by Django 4.2.21 on 2025-06-25 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls_app', '0019_examoptions_remove_examquestions_negativescore_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examoptions',
            name='negativeScore',
        ),
        migrations.RemoveField(
            model_name='examoptions',
            name='positiveScore',
        ),
        migrations.AddField(
            model_name='examquestions',
            name='negativeScore',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='examquestions',
            name='positiveScore',
            field=models.IntegerField(default=0),
        ),
    ]
