# Generated by Django 4.2.21 on 2025-06-25 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls_app', '0020_remove_examoptions_negativescore_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examoptions',
            name='isCorrect',
        ),
    ]
