# Generated by Django 4.2.21 on 2025-06-25 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls_app', '0021_remove_examoptions_iscorrect'),
    ]

    operations = [
        migrations.AddField(
            model_name='examoptions',
            name='optionnumber',
            field=models.IntegerField(default=0),
        ),
    ]
